### ISSUE TITLE
Login in Chrome points to blank page since 1.3.10 (and in 1.3.11beta)

### ISSUE THREAD

**Issue by fiammybe** [ImpressCMS/impresscms#100]
This only happens on a site that is migrated from a previous version. 

After logging in, the user is presented with a blank page. Refreshing that page redirects to the correct user profile page.

**Comment by fiammybe** [comment]
I can confirm this on a 1.3.10 site (the upcoming impresscms site I'm developing) with Chrome. On Edge and Firefox, no problem at all.

**Comment by skenow** [comment]
This works correctly on 1.3.9? Going from 1.3.0 to 1.3.10 breaks it?

**Comment by fiammybe** [comment]
fixed in #504

**Comment by fiammybe** [comment]
Reopening this issue. Logging in from the user.php page is still giving the same problem. It seems the redirect url is not passed correctly the first time.
When logging in with the block, the issue is not there.

**Comment by fiammybe** [comment]
Fixed in #670
