### ISSUE TITLE
Module installation step in installer v2 crashes

### ISSUE THREAD

**Issue by fiammybe** [ImpressCMS/impresscms#1002]
## Describe the bug
Module installation step in installer crashes

## To Reproduce
1. Do the installation routine
2. On the 'module install' page, just leave the system module selected and go further
3. See error (on page /htdocs/install/page_modulesinstall.php)

## Screenshots
Fatal error: Uncaught TypeError: Argument 1 passed to Imponeer\Smarty\Extensions\DBResource\DBResource::getCacheArrayForFile() must be of the type string, null given, called in D:\xampp74\htdocs\icms2\vendor\imponeer\smarty-db-resource\src\DBResource.php on line 136 and defined in D:\xampp74\htdocs\icms2\vendor\imponeer\smarty-db-resource\src\DBResource.php:182 Stack trace: #0 D:\xampp74\htdocs\icms2\vendor\imponeer\smarty-db-resource\src\DBResource.php(136): Imponeer\Smarty\Extensions\DBResource\DBResource->getCacheArrayForFile(NULL) #1 D:\xampp74\htdocs\icms2\vendor\imponeer\smarty-db-resource\src\DBResource.php(108): Imponeer\Smarty\Extensions\DBResource\DBResource->getInfo('system_imageman...') #2 D:\xampp74\htdocs\icms2\vendor\smarty\smarty\libs\sysplugins\smarty_resource_custom.php(56): Imponeer\Smarty\Extensions\DBResource\DBResource->fetch('system_imageman...', NULL, NULL) #3 D:\xampp74\htdocs\icms2\vendor\smarty\smarty\libs\sysplugins\smarty_template_source.php(182): Smarty_Resource_Custom->populate(Object(Smarty in D:\xampp74\htdocs\icms2\vendor\imponeer\smarty-db-resource\src\DBResource.php on line 182

## Server
 - PHP version: 7.4.24
 - PHP is 32/64bit: 64

**Comment by fiammybe** [comment]
@MekDrop Upgrading the smarty-db-resource to 1.1.0 didn't have any effect I'm afraid.

**Comment by fiammybe** [comment]
The issue is due to 2 missing template files for the image manager. But the smart-db-resource should also be capable of handling a missing file naturally :-)

**Comment by MekDrop** [comment]
Yeah that's why #1003 is needed for that.
