### ISSUE TITLE
Error notification in migration script in installer

### ISSUE THREAD

**Issue by fiammybe** [ImpressCMS/impresscms#1004]
## Describe the bug
When doing the migration script in the installer, I see an error notification at the end 👍 

```
In Container.php line 188:

Alias (editor.content) is not being managed by the container or delegates


migrate [-e|--environment ENVIRONMENT] [-c|--config CONFIG] [-t|--config_type CONFIG_TYPE] [-f|--output-format OUTPUT-FORMAT] [--dry] [--first] [--target TARGET] [--dir DIR] [--class CLASS]

```
## To Reproduce
1. Install the latest master
2. go through the steps until you reach the migration script (/htdocs/install/page_tablesfill.php)
3. See error

**Comment by MekDrop** [comment]
I think for this is #800 partial fix. Still after that I need to make some editor to be working in new way.

From what I understand this is also related to composer v2. With older composer it seems everything works as expected.
