### ISSUE TITLE
pagination in the backend generates wrong URLs

### ISSUE THREAD

**Issue by fiammybe** [ImpressCMS/impresscms#102]
In ImpressCMS 1.3.10, I go for example to the blocks page. There, I see that the blocks take 4 pages. When I click on the '2' to go to the second page, I get thrown back to the ACP front page.

When I do the same on 1.3.9, I am merrily taken to the second page.

The problem was checked on other pages with pagination, and is present on 1.3.10, but not on 1.3.9.

**Comment by fiammybe** [comment]
When I investigate this a bit more, the URL generated by the 1.3.9 site is 
"/modules/system/admin.php?fct=blocksadmin&sortsel=title&ordersel=ASC&limitsel=15&startbid=15"

whereas the URL generated by 1.3.10 is 
"/modules/system/admin.php?sortsel=title&ordersel=ASC&limitsel=15&startbid=15"

It seems the fct=blocksadmin is missing (and the fct=somethin in the other cases as well.

**Comment by skenow** [comment]
It must be something from the added filtering in 1.3.10 - I'll sort it out.

**Comment by fiammybe** [comment]
Ok for 1.3.11
