### ISSUE TITLE
Code of conduct on GitHub

### ISSUE THREAD

**Issue by MekDrop** [ImpressCMS/impresscms#103]
So, on GitHub there is new page https://github.com/ImpressCMS/impresscms/community and there is one checkbox unchecked right now... we must fix that! :)

**Comment by MekDrop** [comment]
It seems GitHub use generators and two templates for this purpose. We need to choice one from these. ![screen shot 2017-07-11 at 13 25 44](https://user-images.githubusercontent.com/342641/28064331-d6f6b69a-663c-11e7-9df1-2e75b8dcde5b.png)

**Comment by fiammybe** [comment]
Better one than none :-)
