### ISSUE TITLE
Rename retro branch to something something clearer

### ISSUE THREAD

**Issue by MekDrop** [ImpressCMS/impresscms#105]
We use this branch for 2.0 code. But it easy for anyone from outside to know that? I think we should rename this branch to something clearer.

Maybe we should use version numbers instead like we are doing for 1.3 code?

**Comment by skenow** [comment]
It was a choice made after the 2.0 development branch was started and progressed to a point where we had to go backwards to go forwards. So, I cherrypicked a bunch of commits and went 'retro'. It isn't obvious where our active 2.0 development is taking place. 

The plan was to make this the main 2.0 branch after we get a final for 2.0.0

**Comment by MekDrop** [comment]
Yeah, I understand that but because this 2.0 it takes ages to release I think it would be better to rename that branch into something linked with actual version. Or at least maybe we should do 1.3 branch as default to make for everyone who doesn't do much with icms development less confusing what branch is our actual branch.
