### ISSUE TITLE
MySQL 8 compatibility

### ISSUE THREAD

**Issue by skenow** [ImpressCMS/impresscms#1090]
## Current code is not MySQL 8 compatible
Instances of database updates failing on MySQL 8

## Areas discovered
Adding new users
Registration of new users

## Server
 - MySQL 8.0.x

## Additional Context
When changing the MySQL version on the same server to 5.7, the above actions did succeed.

**Comment by skenow** [comment]
There are additional reserved words in MySQL 8 that are used as column names See https://dev.mysql.com/doc/refman/8.0/en/keywords.html#keywords-new-in-current-series

The easiest way to deal with this is to make sure all queries are using quotes for table and column names.

**Comment by skenow** [comment]
I did escape 1 column name in the insert user method (rank - a new reserved work in MySQL8), and was able to register successfully.

**Comment by fiammybe** [comment]
Long-term solution would be to start using parameterised queries instead of constructing the queries ourselves, but that's a much bigger target than fixing these issues.

**Comment by fiammybe** [comment]
I think @skenow has been doing some work on this for 1.5. Not sure if the entire core is now working with newer MYSQL versions though.

**Comment by skenow** [comment]
Tested installation and all the core functions/areas with PHP8.1 and MySQL 8.0.43-ubuntu - no errors at this point.

**Comment by fiammybe** [comment]
I think we can safely close this one then.
