### ISSUE TITLE
System module always needs to be updated

### ISSUE THREAD

**Issue by skenow** [ImpressCMS/impresscms#1114]
## Describe the bug
Whenever you go to the admin area, you are prompted to update the system module. The update completes successfully, but never registers as being updated

## To Reproduce
1. Go to admin.php

## Expected behavior
After the first system module update, the prompt should not occur

## Additional context
ICMS_SYSTEM_DBVERSION is set to 46 in /include/version.php
/modules/system/include/update.php only goes to 45

**Comment by fiammybe** [comment]
@skenow Is there a reason why DBVersion is 46? There are no DB changes as far as I know, but could it be to trigger the upgrade script to remove files?

**Comment by skenow** [comment]
The constant is what determines whether the upgrade should run. It "assumes" there are db changes to go with it, but that's not always the case. If you want any changes applied, whether to add/remove/move files, or make changes to the database, the constant has to be greater than the current dbversion stored in the db.

**Comment by skenow** [comment]
We do need to trigger an update of the system module with each release. We might be able to switch to using the build info instead of the dbversion - but, we'd have to get the right information stored and checked to do so.

**Comment by skenow** [comment]
Would it be best to have another try-catch section for the ICMS_SYSTEM_DBVERSION = 46, or include in the first try{} portion. In either case, this would be the code to add - 

`		/*  Begin upgrade to version 1.4.3 */
		if (!$abortUpdate) $newDbVersion = 46;
		if ($dbVersion < $newDbVersion) {
			// is there anything to do with this release, other than update the system module and version?		


			/* Finish up this portion of the db update */
			if (!$abortUpdate) {
			$icmsDatabaseUpdater->updateModuleDBVersion($newDbVersion, 'system');
			echo sprintf(_DATABASEUPDATER_UPDATE_OK, icms_conv_nr2local($newDbVersion)) . '<br />';
			}
`

**Comment by skenow** [comment]
Is addressed in PR for 1.4.3 version update

**Comment by fiammybe** [comment]
Thanks @skenow, this is effectively covered in PR #1109
