### ISSUE TITLE
Gravatar should take into account HTTPS/HTTP

### ISSUE THREAD

**Issue by fiammybe** [ImpressCMS/impresscms#113]
When you have a site in HTTPS, the gravatar images are loaded using the HTTP URL. This generates warnings in newer browsers and should be corrected.

**Comment by fiammybe** [comment]
I suppose this is a more widespread problem : every functionality that constructs a URL for a service will need to know if HTTPS traffic is needed or not. I believe it is better to tackle this problem on a level that will be managed by the core (with appropriate overrides via constants or a configuration option, for those borderline cases where the detection isn't working correctly)

**Comment by skenow** [comment]
The core can assist in this - see icms::buildRelevantUrls(). The 'http' index will contain whether the site is running on http or https. This can then be passed to the function for constructing the URL call for the outside service.
