### ISSUE TITLE
codemirror does not install in 2.0 alpha 12

### ISSUE THREAD

**Issue by fiammybe** [ImpressCMS/impresscms#1153]
## Describe the bug
I get the following error when installing the codemirror plugin on a fresh install of icms2 alpha 12 : 
`
Fatal error: Uncaught League\Flysystem\UnableToReadFile: Unable to read file from location: vendor/npm-asset/codemirror/mode/apl. in C:\xampp74\htdocs\davidjanssens.be\vendor\league\flysystem\src\UnableToReadFile.php on line 24
--
1 | 0.2103 | 454008 | {main}( ) | ...\server.php:0
2 | 0.2507 | 733384 | require( 'C:\xampp74\htdocs\davidjanssens.be\htdocs\install\page_modulesinstall.php' ) | ...\server.php:241
3 | 19.7425 | 26644304 | ImpressCMS\Core\Models\ModuleHandler->install( ) | ...\page_modulesinstall.php:80
4 | 23.1943 | 27261848 | ImpressCMS\Core\Extensions\SetupSteps\Module\Install\CopyAssetsSetupStep->execute( ) | ...\ModuleHandler.php:239
5 | 23.2206 | 27268080 | ImpressCMS\Core\Extensions\SetupSteps\Module\Install\CopyAssetsSetupStep->getDefinedAssets( ) | ...\CopyAssetsSetupStep.php:50
6 | 23.3048 | 27278392 | League\Flysystem\Filesystem->readStream( ) | ...\CopyAssetsSetupStep.php:98
7 | 23.3048 | 27278472 | League\Flysystem\Local\LocalFilesystemAdapter->readStream( ) | ...\Filesystem.php:67
`

## To Reproduce
1. check the codemirror module during installation of 2.0 alpha 12
2. Click on '.next'
3. See error

## Expected behavior
no error :-)

## Server
 - PHP version: 7.4
 - PHP is 32/64bit: 64
 - HTTP Server : [Apache, nginx] nginx
 
## Desktop (please complete the following information):
 - OS: [e.g. iOS] windows 10
 - Browser [e.g. chrome, safari] Brave (chrome-based)
 - Version [e.g. 22] 1.34.81

## Additional context
local dev running under valet for windows

**Comment by fiammybe** [comment]
as a matter of fact, the folder vendor\npm-asset\codemirror exists on my computer, but does not contain a subfolder 'apl'

**Comment by MekDrop** [comment]
codemirror was updated and I think this issue should be now fixed. closing
