### ISSUE TITLE
Unable to install - data type error in database setup

### ISSUE THREAD

**Issue by fiammybe** [ImpressCMS/impresscms#1158]
## Describe the bug
I have the following error when configuring the db connection (page_dbconnection.php) : 
`Fatal error: Uncaught TypeError: strtolower() expects parameter 1 to be string, int given in /home/icmsdev/domains/impresscms.dev/vendor/phpexperts/laravel-env-polyfill/src/env-shim.php:47 Stack trace: #0 /home/icmsdev/domains/impresscms.dev/vendor/phpexperts/laravel-env-polyfill/src/env-shim.php(47): strtolower(0) #1 /home/icmsdev/domains/impresscms.dev/vendor/phpexperts/laravel-env-polyfill/src/env-shim.php(90): AAutoloadFirst\PHPExperts\env('DB_PCONNECT', 0) #2 /home/icmsdev/domains/impresscms.dev/core/Providers/DatabaseServiceProvider.php(42): env('DB_PCONNECT', 0) #3 [internal function]: ImpressCMS\Core\Providers\DatabaseServiceProvider->ImpressCMS\Core\Providers\{closure}() #4 /home/icmsdev/domains/impresscms.dev/vendor/league/container/src/Definition/Definition.php(239): call_user_func_array(Object(Closure), Array) #5 /home/icmsdev/domains/impresscms.dev/vendor/league/container/src/Definition/Definition.php(198): League\Container\Definition\Definition->resolveCallable(Object(Closure)) #6 /home/icmsdev/domains/impre in /home/icmsdev/domains/impresscms.dev/vendor/phpexperts/laravel-env-polyfill/src/env-shim.php on line 47`

## To Reproduce
1. Install your site
2. When on he page_dbconnection.php, insert your database info
3. click 'next'

## Expected behavior
Going to the next page of the installer

## Server
 - PHP version: 7.4
 - PHP is 32/64bit: 64bit
 - HTTP Server : Apache AND nginx, tested both

## Additional context
latest code as of 8 feb 2022

**Comment by fiammybe** [comment]
@MekDrop could you have a look at this one please?

**Comment by MekDrop** [comment]
I will but I can't promise ASAP for right now.

**Comment by fiammybe** [comment]
sure, no problem!

**Comment by Nokline** [comment]
still an issue, can't set up the database properly... Was able to fix by removing strtolower in vendor/phpexperts/laravel-env-polyfill/src/env-shim.php line 47. Just a temporary fix to get it working for me... Hopefully I won't run into any more errors in the future...

**Comment by MekDrop** [comment]
Thanks @Nokline for the idea!

And sorry for the delay. Some real live things prevented me to look faster into.

I created a pull request to this lib repo and I hope everything will soon be ok.
