### ISSUE TITLE
FILTER_SANITIZE_STRING is deprecated in PHP 8.1

### ISSUE THREAD

**Issue by fiammybe** [ImpressCMS/impresscms#1159]
## Describe the bug
the use of FILTER_SANITIZE_STRING is no longer allowed. This creates problems in \core\DataFilter.php

**Comment by MekDrop** [comment]
https://stackoverflow.com/a/69207369 possible solutions

**Comment by skenow** [comment]
Perhaps it's time to rethink how we protect against XSS and SQli - our current approach has room for improvement and did cause a few developers to fork (Julian) or create something completely different (Simon).

**Comment by fiammybe** [comment]
Until we review our filtering strategy (as proposed by @skenow in the chat a few weeks ago) this still needs to be fixed. PHP 8.1 is almost superseded by a new version

**Comment by MekDrop** [comment]
I will look into this.
