### ISSUE TITLE
Content subpage navigation does not work in module admin

### ISSUE THREAD

**Issue by skenow** [ImpressCMS/impresscms#124]
This is related to #102 - the top level navigation works, but when you click to view pages related to the top level page, the navigation links are missing a key parameter (content_pid).

To address, we'll need a way for modules to specify get/post parameters for their module, and for icms_ipf_view_Table to add them to the filter arrays.

**Comment by skenow** [comment]
Is the content module the only module that uses additional parameters like this?

**Comment by fiammybe** [comment]
The question I ask myself is whether this information is really necessary in the URL. For example, when you look at a page with a short URL defined, you will have a page like this : 
https://www.impresscms.org/modules/content/content.php?content_id=6&page=main-page

Notice the content_id parameter and the page parameter. You only need 1.

When you are on a page, the page has access to its own data, and can get its parent page Id. In my opinion, there is no need to have that information in the url. If that is the way it works, we need to change it.

**Comment by fiammybe** [comment]
is this 1.3 or also in 2.0?

**Comment by fiammybe** [comment]
Hi @skenow , could you verify in the current state of 2.0 alpha if this problem is still there?

**Comment by fiammybe** [comment]
I haven't encountered the issue lately. too many changes to identify which code change fixed this, but closing this one off.
