### ISSUE TITLE
Missing ";" in \htdocs\modules\system\include\update.php

### ISSUE THREAD

**Issue by mambax7** [ImpressCMS/impresscms#1357]
During installation of 1.5.0 RC, when it gets to "Install Modules" step in /install/page_modulesinstall.php
```
This page cannot be displayed due to an internal error.

You can provide the following information to the administrators of this site to help them solve the problem:

Error: syntax error, unexpected '}', expecting ',' or ';'

File: \htdocs\modules\system\include\update.php
Line: 157
```

**Comment by mambax7** [comment]
After fixing it, and trying to continue, I'm getting an empty page with:
```
Current version: 40
Updating to version 46
```
This is using PHP 7.3.33 on Wampserver

**Comment by MekDrop** [comment]
This it seems exists in 1.5.0 release but not in the latest 1.5.x branch. Probably it was already fixed? :/

**Comment by fiammybe** [comment]
Probably something that I forgot to include on git. I'll verify and fix if needed

**Comment by mambax7** [comment]
Awesome! Thanks!

**Comment by fiammybe** [comment]
Hi @mambax7 I just verified it with the latest code, and this issue is no longer present. I'm closing it now.
Thanks for the report!

**Comment by mambax7** [comment]
Thanks for the update!
