### ISSUE TITLE
Figure out what to do with some old XML classes

### ISSUE THREAD

**Issue by MekDrop** [ImpressCMS/impresscms#145]
We have `htdocs/libraries/xml/saxparser.php` and `htdocs/libraries/xml/xmltaghandler.php` in our core. These files comes from https://sourceforge.net/p/extremephp/wiki/Home/. Bad thing that this lib doesn't have composer support and also big. What we should do we these files?

**Comment by fiammybe** [comment]
We're building version 2.0, so we could break some backward compatibility. The most important question is : what are these used for exactly?
themesetparser.php is nowhere used in the core as far as I could see
saxparser.php and xmltaghandler.php  are only used in Xoops variants of an RSS class and RPC classes - both unused at the moment.

We could remove them in my opinion. The RSS class is replaced by simplepie and the rpc classes should no longer be used.
