### ISSUE TITLE
backport PHP7 installer

### ISSUE THREAD

**Issue by fiammybe** [ImpressCMS/impresscms#146]
Backport the changes to the installer in icms 1.3 so that we can start using icms 1.3 with PHP 7 right now

**Comment by fiammybe** [comment]
I'm not really looking at backporting the composer functionality right now, so I'll  have to hardcode some stuff :-(

**Comment by MekDrop** [comment]
I could fix installer but than we have another problem - Protector, that use many old style mysql methods. In 2.0 it's not a big problem because we have there new properties system and frontend controller functionality. #159 adds there even some more security. But what todo with 1.3.x I'm not sure.

**Comment by fiammybe** [comment]
Backport to PHP7 would be nice, but not at all a priority. If you could just fix the installer, that’s one thing already, but don’t waste time on the rest.

**Comment by fiammybe** [comment]
We will focus on 2.0, so I don't think we'll backport the installer for the time being
