### ISSUE TITLE
PHP8.1 : icms module object countable error

### ISSUE THREAD

**Issue by fiammybe** [ImpressCMS/impresscms#1495]
Error: count(): Argument #1 ($value) must be of type Countable|array, bool given

File: /home/fiammybe/domains/davidjanssens.be/public_html/libraries/icms/module/Object.php
Line: 345

**Comment by skenow** [comment]
I think we'll find similar cases throughout the code base - in the cases I'm finding, changing from count() to is_array() is sufficient

**Comment by fiammybe** [comment]
In this case, it looks like the only reason this count is used, is to check in the template whether we are at the last of the submenus. But that can be taken care of in the template itself, so this shouldn't be needed. I'll try to rewrite this so it keeps running the same way, but cleaner :-)
