### ISSUE TITLE
Switch defining constants in sdata folder into .env

### ISSUE THREAD

**Issue by MekDrop** [ImpressCMS/impresscms#150]
I think it's easier way to find and modify main settings for ICMS installation. And it's a lot easier way to switch development environment into production than what we use at current moment.

[vlucas/phpdotenv](https://github.com/vlucas/phpdotenv) is most popular lib for handling .env files.

**Comment by skenow** [comment]
Anyone who uses the term "automagically" (vlucas does) has me shaking my head. There's nothing auto or magic involved.

**Comment by MekDrop** [comment]
There are other similar libs like vlucas/phpdotenv. For example m1/env. If this could help I think we could use another.

At current moment when I switch branch, I need again to reinstall ICMS. Also, if I switch dev to prod is same. I want rebuild vagrant box - again possible some problems, because unattended install is very tricky. So, this would help to solve such issues faster. Yeah, it maybe can be less secure than we have now but I think in most cases this would be enough - Laravel and some other popular frameworks uses it.
