### ISSUE TITLE
Replace htdocs/libraries/icms/core/Filesystem.php with league/flysystem

### ISSUE THREAD

**Issue by MekDrop** [ImpressCMS/impresscms#151]
Currently we do not have any support for FTP/FTPS or cloud hosting file providers. Our filesystem class needs also a bit cleanup. So, it would be great to replace all our functionality for files with good package [league/flysystem](http://flysystem.thephpleague.com).

**Comment by fiammybe** [comment]
Fine with me :-) flysystem was on my radar for some time as well

**Comment by MekDrop** [comment]
http://knplabs.github.io/Gaufrette/ could be alternative for this task.

**Comment by MekDrop** [comment]
It seems this isn't possible with our current uses cases. So closing.
