### ISSUE TITLE
Upgrade does not remove banners db tables or configuration entries

### ISSUE THREAD

**Issue by skenow** [ImpressCMS/impresscms#1528]
## Description
banner, bannerclient, and bannerfinish all remain in the database after an upgrade; ACP > Preferences > General : Activate banner ads option still exist

## Additional context
The installation procedures and language files have been updated so new installs don't have these, we need to adjust for upgrades

**Comment by skenow** [comment]
Should this be optional? Will webmasters want to retrieve data for banners they have been using?

**Comment by fiammybe** [comment]
There are no modules that make use of this information at the moment, so I wouldn't invest time in that.

**Comment by skenow** [comment]
Good point - the only way to get the information is to go to a database backup. In finishing this one off, I'll make sure the upgrade message includes being sure there is a backup of the db and files (should be part of every upgrade, IMO)
