### ISSUE TITLE
CKeditor config lacking ImpressCMS customizations

### ISSUE THREAD

**Issue by skenow** [ImpressCMS/impresscms#1529]
There were custom toolbars based on user group in config.js that are still mentioned in formCkeditor.php. The current config.js appears to be the CKeditor default.

**Comment by yasmoto1995** [comment]
I 've learnt lots of things here.
Can you explain more detaily about using CKeditor?
Best Regard

**Comment by fiammybe** [comment]
Yes, it seems that the custom configuration in https://github.com/ImpressCMS/impresscms/blob/2.0.x/htdocs/editors/CKeditor/formCkeditor.php > initCKEditor is not taken into account.

**Comment by skenow** [comment]
The render() function in formCkeditor.php has logic to determine which toolbar configuration to use - they were defined in config.js.
