### ISSUE TITLE
use of removed $icmsModule througout the core

### ISSUE THREAD

**Issue by fiammybe** [ImpressCMS/impresscms#1538]
the global variable $icmsModule is no longer available, and should be replaced by icms::$module. But I still see lots of places in the core where that variable is used.

**Comment by fiammybe** [comment]
It's not so easy I fear. The $icmsModule variable is sometimes used internally, so it's not as easy as replacing them all with icms::$module :-(

**Comment by skenow** [comment]
Yes, I have found places where it is defined and used - got to review them 1 by 1

**Comment by skenow** [comment]
And I think I got quite a few of them changed while working on the PHP7/8 compliance

**Comment by skenow** [comment]
I stand corrected - I just did a search and there are over 250 occurrences still left

**Comment by fiammybe** [comment]
I tried migrating the ImpressCMS site to 2.0 RC2 and it bombed on me :-( Most of the issues will be the use of $icmsModule in the modules used on the site, but I'm going through the files to see if I can get it working on the beta site. After that, I can re-try the migration from a fresh dump.
This is blocking for the 2.0 release I'm afraid.

**Comment by fiammybe** [comment]
Looks like most of the issues I had with the migration of the ImpressCMS.org site were module related.

**Comment by fiammybe** [comment]
this should be fixed by #1555 . If there are some more cases lingering about, they will surface in due course.
