### ISSUE TITLE
Admin Control Panel layout is missing css properties

### ISSUE THREAD

**Issue by skenow** [ImpressCMS/impresscms#1586]
![image](https://github.com/user-attachments/assets/126d215f-47e0-4255-8b9e-99828d9c92b5)

A fresh install of the 2.0.x branch results in this layout for the admin control panel. Without icms.css, there are some elements that need to be moved to the themes. See #1563

**Comment by fiammybe** [comment]
Good find, I am experimenting with new admin layouts, so I thought I broke something there. I'll simply add the icms.css to the admin theme, wouldn't that be a quick fix solution?

**Comment by skenow** [comment]
I don't know if it all needs to be added back in, there are some attributes that definitely need to get moved to the theme css. I copied the attributes that included cpicon and that resolved this particular area. I haven't gone through all the other areas thoroughly.
