### ISSUE TITLE
user table cleanup fails 

### ISSUE THREAD

**Issue by fiammybe** [ImpressCMS/impresscms#1589]
https://github.com/ImpressCMS/impresscms/blob/4e4abf771273e65960f54acd67a8eb6d74dc48fc/htdocs/modules/system/include/update.php#L222

When upgrading from 2.0 b1 to 2.0b2 I get the following error : 
Current version: 47
Updating to version 48
Successfully updated to version 47
This page cannot be displayed due to an internal error.

You can provide the following information to the administrators of this site to help them solve the problem:

Error: implode(): Argument #1 ($array) must be of type array, string given

File: /*/*/*/*/*/*/libraries/icms/db/legacy/updater/Table.php
Line: 559
Backtrace:
/modules/system/include/update.php (222)
/modules/system/admin/modulesadmin/modulesadmin.php (1376)
/modules/system/admin/modulesadmin/main.php (323)
/modules/system/admin.php (137) 

This also results in the DbVersion not being updated.

**Comment by skenow** [comment]
Were the fields already removed from your database? Seems like we'll need to add that as a possibility
