### ISSUE TITLE
Start using dependency injector

### ISSUE THREAD

**Issue by MekDrop** [ImpressCMS/impresscms#161]
Right now we use have some classes that have service methods. These methods are loaded when ICMS boots. It works, but we have few problems with such implementation:
- if we need new service for some composer package we need to write some extra class
- all our services are always loaded (so, we are loosing speed if not all services are needed)
- it harder to split icms lib in multiple composer packages (for easier maintaining)
By switching to DI lib, I think we could solve these issues.

I found these composer libs that we could use:
- [Aura.Di](http://auraphp.com/packages/3.x/Di/)
- [league/container](http://container.thephpleague.com)
- [php-di/php-di](http://php-di.org)
- [pimple/pimple](https://pimple.symfony.com)

So, what do you think?

**Comment by fiammybe** [comment]
Steve and I talked about introducing more patterns in the code, and DI was one of them. We didn't get as far as to identify what would be the best one to start with, so it more or less ended with that discussion. 

When I look at the different composer libs there, I would prefer php-di, because of its very complete documentation. DO you have experience with one of these libraries?

**Comment by MekDrop** [comment]
I think I have used pimple some time ago for test project for my job. 

php-di for me looks easiest however it seems it doesn't have support for services providers like league/container has. I'm not sure what way would be better to describe all dependencies. Write in classes as with league/container (as some popular frameworks like laravel does) we could do or in nodejs style like php-di does.

**Comment by fiammybe** [comment]
When it comes to one of the basics of ImpressCMS until now, we favored convention over configuration. I think that is what php-di explains with their first paragraph on their front page, that it can cover 80% by guessing which dependencies to inject. Looking around, some people think service locators are not a good practice, so I'm not sure this would be a breaking issue to start with. If we get to the point where the 2.x codebase really NEEDS the service locators, I think rewriting the existing DI with another library will be much less work than introducing the DI in the first place.

**Comment by MekDrop** [comment]
Good point! I think I will try with PHP-DI this weekend something to do.

**Comment by MekDrop** [comment]
Oh... I just remember... before I do something with this one, I need that #159 be merged first. Our current configuration way is a bad choice for using with DI.

**Comment by MekDrop** [comment]
Ok it seems that if use [phpleague/route](http://route.thephpleague.com) for #189 we are already getting [phpleague/container](http://container.thephpleague.com). Maybe we should use this one or should I try to find another router?
