### ISSUE TITLE
Replace our custom caching with some lib

### ISSUE THREAD

**Issue by MekDrop** [ImpressCMS/impresscms#162]
We use caching in some places (f.e. admin menu), however every such place use different way how deals with such task and bad thing is that no configuration to such behavior is impossible. Usually that means it's hard to move some caching data to memcache or any faster place than disk folder. So it would be a good idea to start using something better to make possible to use ICMS in high traffic websites.

From what I found, I see two options for us:
- [apix/cache](https://github.com/apix/cache)
- [zendframework/zend-cache](https://zendframework.github.io/zend-cache/)

Apix seems easier but zend-cache seems for me powerful. 

What do you think?

**Comment by fiammybe** [comment]
The caching mechanism we currently use is the one from Smarty. Doesn’t Dwoo have a similar one? Smarty had problems with erasing specific content fromt he case, perhaps Dwoo doesn’t.

Our Admin still has quite a few pages without smarty-templated pages, and those are a problem of course

**Comment by MekDrop** [comment]
I mean for caching data not templates. F.e. we cache admin menu in file that is generated from many icms_version.php files and cached as serialized array. I think somewhere in our code I saw another few things that use such behavior. What to do with templates is another question.

**Comment by MekDrop** [comment]
Ah... I just wrote another comment and I have remembered... some ObjectHandlers in our core use caching in arrays. I think caching lib could possible improve speed in some cases there.

**Comment by fiammybe** [comment]
@mekdrop I think we can close this, as #170 is merged?

**Comment by MekDrop** [comment]
agree
