### ISSUE TITLE
Replace our router with some composer package

### ISSUE THREAD

**Issue by MekDrop** [ImpressCMS/impresscms#189]
Right now our router is very primitive thing. Also, composer lib would make it easier for us to manage and less code. 

There are few  router libs, but I think [Route from PHPLeague](http://route.thephpleague.com) would fit best for us. It has support for custom router strategies and is [PSR-7](https://www.php-fig.org/psr/psr-7/) compliant. So, I think it will be easy in future replaceable if we decide to choice another router lib.

**Comment by fiammybe** [comment]
Route from phpleague looks nice, and I would propose to use guzzlehttp/psr7 as PSR7 package (because you need to have one of those as well). What do you mean with our 'router'? The symlinks perhaps?

**Comment by MekDrop** [comment]
Few years ago for 2.0 I have created some basic router. See https://github.com/ImpressCMS/impresscms/blob/retro/htdocs/libraries/icms/controller/Handler.php That I mean by saying 'our'. But it's very basic. So, I though to replace it with something better. 

#159 pull request adds proxy routing for old style icms modules. So, probably this task also replaces partially what I did for that task.

Yeah, guzzlehttp/psr7 looks good. I'm not sure if this would be same task but maybe we could look into.

**Comment by MekDrop** [comment]
It seems #409 must be implemented first.

**Comment by fiammybe** [comment]
I am curious : why is #409 a dependency? The routing is not a module as far as I know?

**Comment by MekDrop** [comment]
Right now module installations stuff use some big monolith functions that outputs/returns plain HTML and these functions are hard to extend. Also, current way has problems for using routes them in composer.json.
