### ISSUE TITLE
Use composer as our command line interface?

### ISSUE THREAD

**Issue by MekDrop** [ImpressCMS/impresscms#204]
Right now we have `cmd.php` for executing our command line commands. And every framework uses a different one command line manager. Usually you need to guest their name. I thought maybe instead of separate command we could add same support to composer install (yeah, it has custom commands support trought composer.json or custom plugins). 

So, instead of `./cmd.php version` (this command is not implemented yet) user could run `composer impresscms::version`. Instead of `./cmd.php queue` (this command also not implemented) `composer queue`.

Is this a good idea? If yes, we don't need to implement #190

**Comment by fiammybe** [comment]
Interesting idea :-)
