### ISSUE TITLE
the 'general preferences' page gives a blank page on PHP7.2

### ISSUE THREAD

**Issue by fiammybe** [ImpressCMS/impresscms#232]
I have integrated PR #227, PR #228 and PR #229 (impresscms/impresscms:retro) up to date, and most of the pages work well. When I go to <site_url>/modules/system/admin.php?fct=preferences&op=show&confcat_id=1 I get a nice blank page.

The problem is only on PHP 7.2, tested and this works ok on PHP 7.1 and PHP 5.6

**Comment by MekDrop** [comment]
It seems that was fixed in #245 when I tried to fix tests for changes that triggered same issue.
