### ISSUE TITLE
Enable inline Smarty debug console

### ISSUE THREAD

**Issue by MekDrop** [ImpressCMS/impresscms#254]
Many new browsers automatically blocks popups and that's why Smarty debug console will be not shown. Also, debuging with popup doesn't look good. 

I think we could solve this by modifying `debug.tpl` from smarty distribution in a way that output should be redirected not to a popup but to debug console.

**Comment by fiammybe** [comment]
Good suggestion. As a first improvement of the debug experience this is a good one
