### ISSUE TITLE
Would it be safe to remove version.php and replace with class that reads version info from composer?

### ISSUE THREAD

**Issue by MekDrop** [ImpressCMS/impresscms#260]
I think this would be better way for handling versioning. But what do you think?

**Comment by fiammybe** [comment]
as I understand, version.php contains the version information of the core, independent of the system module. We have the name, the version, the status, the build number and the DB version number in there. status, build and db version are the elements I think are not yet available elsewhere

**Comment by MekDrop** [comment]
Right now we could get version and status from composer. Yeah DB version right now can't be replaced. We need to implement true database migrations first.

I'm not sure why we need build number. And why there is such lines:
```php
// For backward compatibility with XOOPS
define('XOOPS_VERSION', ICMS_VERSION_NAME);
```

Does it means that somewhere in our modules such functionality is used?

**Comment by fiammybe** [comment]
The XOOPS stuff is old and should no longer be used in 2.0, so we can safely remove it and fix the cases where it would still be used

**Comment by fiammybe** [comment]
I tried a small hack as a solution in the middle where I change the version.php file to go and read the necessary values from the composer.json. It works, but there is much information that isn't in the composer file.

**Comment by fiammybe** [comment]
Response : YES. Closing as duplicate of #261
