### ISSUE TITLE
pagination doesn't link to correct url when in a subfolder

### ISSUE THREAD

**Issue by fiammybe** [ImpressCMS/impresscms#264]
I included several merge requests for alpha7 (#245, #223, #252) , and now the pagination isn't working anymore in the tables in the acp. The URL generated does not contain the subfolder.
Check the blocks page or the mimetype page. The pagination URL is incorrect, but the edit links are ok.

**Comment by MekDrop** [comment]
I think this bug already exists in alpha 6 :/
