### ISSUE TITLE
I can not install Alpha 6 - why is that?

### ISSUE THREAD

**Issue by AlexL777** [ImpressCMS/impresscms#266]
Hello Developers,

I can not install Alpha 6 on root server. I have the directory `/htdocs` in the root directory and this I surf in the browser. It will probably then forward to `/install`.

Unfortunately, the server only shows errors and no installation routine.

What am I doing wrong?

Is it possibly due to the .htaccess file?

Thanks in advance.

**Comment by MekDrop** [comment]
Could you be more specific about what errors you see? 

It should forward to /install or if your server is misconfigured show something useful what to do next. Or maybe you see something and that confuses you?

**Comment by AlexL777** [comment]
The browser under https://impresscms.liebrechts-portfolio.de/htdocs shows that it is a misconfiguration of the server. I use Centos 7.4, Plesk and PHP 7.1.

If this can help you.

At first I thought it was the .htaccess. Can be completely different.

**Comment by MekDrop** [comment]
Uh... ok, first thing is that if you install ImpressCMS on server I recommend to rename `htdocs` folder into something that your public web folder is called. Usually that is `public_html`, `www`, `public`, `wwwroot` folder. Than move everything by one folder up. F.e. if your public web folder is `/home/alex/impresscms/public_html`, you should rename `/home/alex/impresscms/public_html/htdocs` to `/home/alex/impresscms/public_html/public_html` and than move all `/home/alex/impresscms/public_html` content to `/home/alex/impresscms/`. This would hide .env file with settings from public visitors and makes configuration data secure.

For me looks strange that if I go also to https://impresscms.liebrechts-portfolio.de I see same 500 error. And on upper folder there is no .htaccess file. I can't even access https://impresscms.liebrechts-portfolio.de/htdocs/help.html that is static so it doesn't seems issue with PHP files :/

Also did you run `composer install`?

Try rename .htaccess file and see if you see something. 

Also, if you have access to your apache logs and could share that also would be helpful.

**Comment by AlexL777** [comment]
`[Thu Apr 05 14:20:02.907130 2018] [core:alert] [pid 3412:tid 139757582427904] [client 217.226.206.159:50193] /var/www/vhosts/liebrechts-portfolio.de/impresscms.liebrechts-portfolio.de/.htaccess: Unsupported HTTP response code 421, referer: https://impresscms.liebrechts-portfolio.de/public
[Thu Apr 05 14:20:07.488854 2018] [core:alert] [pid 3455:tid 139757599213312] [client 217.226.206.159:50194] /var/www/vhosts/liebrechts-portfolio.de/impresscms.liebrechts-portfolio.de/.htaccess: Unsupported HTTP response code 421
[Thu Apr 05 14:20:07.668765 2018] [core:alert] [pid 3455:tid 139757590820608] [client 217.226.206.159:50195] /var/www/vhosts/liebrechts-portfolio.de/impresscms.liebrechts-portfolio.de/.htaccess: Unsupported HTTP response code 421, referer: https://impresscms.liebrechts-portfolio.de/
[Thu Apr 05 14:20:09.783261 2018] [core:alert] [pid 3412:tid 139757574035200] [client 217.226.206.159:50196] /var/www/vhosts/liebrechts-portfolio.de/impresscms.liebrechts-portfolio.de/.htaccess: Unsupported HTTP response code 421
[Thu Apr 05 14:20:09.957054 2018] [core:alert] [pid 3455:tid 139757582427904] [client 217.226.206.159:50197] /var/www/vhosts/liebrechts-portfolio.de/impresscms.liebrechts-portfolio.de/.htaccess: Unsupported HTTP response code 421, referer: https://impresscms.liebrechts-portfolio.de/
[Thu Apr 05 14:20:13.435793 2018] [core:alert] [pid 3455:tid 139757574035200] [client 217.226.206.159:50198] /var/www/vhosts/liebrechts-portfolio.de/impresscms.liebrechts-portfolio.de/.htaccess: Unsupported HTTP response code 421
[Thu Apr 05 14:20:13.615642 2018] [core:alert] [pid 3455:tid 139757557249792] [client 217.226.206.159:50200] /var/www/vhosts/liebrechts-portfolio.de/impresscms.liebrechts-portfolio.de/.htaccess: Unsupported HTTP response code 421, referer: https://impresscms.liebrechts-portfolio.de/
[Thu Apr 05 14:21:48.795310 2018] [proxy_fcgi:error] [pid 3455:tid 139757565642496] [client 217.226.206.159:50211] AH01071: Got error 'PHP message: PHP Warning:  include_once(/var/www/vhosts/liebrechts-portfolio.de/mainfile.php): failed to open stream: No such file or directory in /var/www/vhosts/liebrechts-portfolio.de/impresscms.liebrechts-portfolio.de/index.php on line 102\nPHP message: PHP Warning:  include_once(): Failed opening '/var/www/vhosts/liebrechts-portfolio.de/mainfile.php' for inclusion (include_path='.:/opt/plesk/php/7.2/share/pear') in /var/www/vhosts/liebrechts-portfolio.de/impresscms.liebrechts-portfolio.de/index.php on line 102\nPHP message: PHP Fatal error:  Uncaught Error: Class 'icms' not found in /var/www/vhosts/liebrechts-portfolio.de/impresscms.liebrechts-portfolio.de/index.php:133\nStack trace:\n#0 {main}\n  thrown in /var/www/vhosts/liebrechts-portfolio.de/impresscms.liebrechts-portfolio.de/index.php on line 133\n'
[Thu Apr 05 14:21:55.828592 2018] [core:alert] [pid 3455:tid 139757506893568] [client 217.226.206.159:50212] /var/www/vhosts/liebrechts-portfolio.de/impresscms.liebrechts-portfolio.de/public/.htaccess: Unsupported HTTP response code 421
[Thu Apr 05 14:22:02.922843 2018] [core:alert] [pid 3412:tid 139757481715456] [client 217.226.206.159:50216] /var/www/vhosts/liebrechts-portfolio.de/impresscms.liebrechts-portfolio.de/public/.htaccess: Unsupported HTTP response code 421
[Thu Apr 05 14:22:09.192150 2018] [core:alert] [pid 3455:tid 139757464930048] [client 217.226.206.159:50218] /var/www/vhosts/liebrechts-portfolio.de/impresscms.liebrechts-portfolio.de/public/.htaccess: Unsupported HTTP response code 421`

The file mainfile.php is not found by the installer as it is called in the error message. But under https://liebrechts-portfolio.de this file is not synonymous and can not be there.

My blog is under `/liebrechts-portfolio.de/impresscms.liebrechts-portfolio.de`

It is a Plesk subdomain. Hm ... if it has something to do with it.

**Comment by MekDrop** [comment]
Try delete `	ErrorDocument 421 error.php?e=421` from .htaccess file. Does it helped?

**Comment by AlexL777** [comment]
I just made in both .htaccess files.

At https://impresscms.liebrechts-portfolio.de/public/, a white page with the ImpressCMS favicon is displayed in the browser.

Something is missing.

**Comment by AlexL777** [comment]
`[Thu Apr 05 14:34:09.200321 2018] [proxy_fcgi:error] [pid 14791:tid 139757481715456] [client 217.226.206.159:50317] AH01071: Got error 'PHP message: PHP Warning:  include_once(/var/www/vhosts/liebrechts-portfolio.de/mainfile.php): failed to open stream: No such file or directory in /var/www/vhosts/liebrechts-portfolio.de/impresscms.liebrechts-portfolio.de/index.php on line 102\nPHP message: PHP Warning:  include_once(): Failed opening '/var/www/vhosts/liebrechts-portfolio.de/mainfile.php' for inclusion (include_path='.:/opt/plesk/php/7.2/share/pear') in /var/www/vhosts/liebrechts-portfolio.de/impresscms.liebrechts-portfolio.de/index.php on line 102\nPHP message: PHP Fatal error:  Uncaught Error: Class 'icms' not found in /var/www/vhosts/liebrechts-portfolio.de/impresscms.liebrechts-portfolio.de/index.php:133\nStack trace:\n#0 {main}\n  thrown in /var/www/vhosts/liebrechts-portfolio.de/impresscms.liebrechts-portfolio.de/index.php on line 133\n'
[Thu Apr 05 14:34:12.723324 2018] [proxy_fcgi:error] [pid 14791:tid 139757615998720] [client 217.226.206.159:50321] AH01071: Got error 'PHP message: PHP Warning:  include_once(/var/www/vhosts/liebrechts-portfolio.de/mainfile.php): failed to open stream: No such file or directory in /var/www/vhosts/liebrechts-portfolio.de/impresscms.liebrechts-portfolio.de/index.php on line 102\nPHP message: PHP Warning:  include_once(): Failed opening '/var/www/vhosts/liebrechts-portfolio.de/mainfile.php' for inclusion (include_path='.:/opt/plesk/php/7.2/share/pear') in /var/www/vhosts/liebrechts-portfolio.de/impresscms.liebrechts-portfolio.de/index.php on line 102\nPHP message: PHP Fatal error:  Uncaught Error: Class 'icms' not found in /var/www/vhosts/liebrechts-portfolio.de/impresscms.liebrechts-portfolio.de/index.php:133\nStack trace:\n#0 {main}\n  thrown in /var/www/vhosts/liebrechts-portfolio.de/impresscms.liebrechts-portfolio.de/index.php on line 133\n'`

**Comment by MekDrop** [comment]
Thanks for finding and validating a bug! 

About another bug I'm not why paths become incorrect. I'll try to look later why this could happen. There is chance that ICMS installer still has issues with PHP 7.2. I'm doing most tasks on PHP 7.0, so there is chance that I have missed something.

Still, I don't think so that if this is issue from ICMS installer side it would be fixed sooner than alpha 7 will be released (good thing that @fiammybe is working on that and we hope to do that in next few weeks).

**Comment by AlexL777** [comment]
No problem. I also wanted to know after I learned that you were bringing the Alpha 6 out. I'm also a CMS blogger and I'm working on OpenSource CMS.

I'll wait until you're ready, then I'll be happy to install it.

**Comment by fiammybe** [comment]
Hi @AlexL777 , we released the Alpha7 version, could you check if the problem has been solved?

Thanks!

**Comment by AlexL777** [comment]
Hello,

the index.php does not work. It should probably end up in the browser: "`/htdocs/index.php`", but the browser does not forward to it. Do I have to change something at the .htaccess in the directory `/htdocs`?

There are these errors in the backend under `/htdocs/modules/system/admin.php?fct=pages`.

`7
Uncaught exception
Message: Call to protected method icms_module_Handler::checkModuleAccess() from context 'ImpressCMS\Core\Providers\ModuleServiceProvider'
Code: 0
File: /var/www/vhosts/liebrechts-portfolio.de/impresscms.liebrechts-portfolio.de/core/providers/ModuleServiceProvider.php
Line: 49
Trace:
#0 [internal function]: ImpressCMS\Core\Providers\ModuleServiceProvider->ImpressCMS\Core\Providers\{closure}()
#1 /var/www/vhosts/liebrechts-portfolio.de/impresscms.liebrechts-portfolio.de/vendor/league/container/src/Definition/CallableDefinition.php(21): call_user_func_array(Object(Closure), Array)
#2 /var/www/vhosts/liebrechts-portfolio.de/impresscms.liebrechts-portfolio.de/vendor/league/container/src/Container.php(297): League\Container\Definition\CallableDefinition->build(Array)
#3 /var/www/vhosts/liebrechts-portfolio.de/impresscms.liebrechts-portfolio.de/vendor/league/container/src/Container.php(90): League\Container\Container->getFromThisContainer('module', Array)
#4 /var/www/vhosts/liebrechts-portfolio.de/impresscms.liebrechts-portfolio.de/include/common.php(137): League\Container\Container->get('module')
#5 /var/www/vhosts/liebrechts-portfolio.de/impresscms.liebrechts-portfolio.de/mainfile.php(29): include('/var/www/vhosts...')
#6 /var/www/vhosts/liebrechts-portfolio.de/impresscms.liebrechts-portfolio.de/htdocs/index.php(102): include_once('/var/www/vhosts...')
#7 {main}`

Maybe you can take a closer look.

Otherwise, I had to update Composer. Only then did the installation process work. In the error logs I saw that the autoload.php was missing. Hence the composer update or install.

Thank you.

**Comment by fiammybe** [comment]
This is correct, you cannot just download the code anymore and run installer, you need to get the external libraries using composer, and that also generates the autoloader file.
I will create a separate bug for the forward to the index.php, because I'm getting the same results now in the current version.
