### ISSUE TITLE
admin page of modules gives exception

### ISSUE THREAD

**Issue by fiammybe** [ImpressCMS/impresscms#295]
I tried this on several modules, and I get the same issue : 

Profile module:
```
    Uncaught exception
    Message: Call to undefined function icms_cp_header()
    Code: 0
    File: C:\xampp71\htdocs\unifya7\modules\profile\admin\user.php
    Line: 17
    Trace: 
    #0 C:\xampp71\htdocs\unifya7\htdocs\index.php(114): require()
    #1 {main}
```
News module:

    Uncaught exception
    Message: Call to undefined function icms_cp_header()
    Code: 0
    File: C:\xampp71\htdocs\unifya7\modules\news\admin\article.php
    Line: 137
    Trace: 
    #0 C:\xampp71\htdocs\unifya7\htdocs\index.php(114): require()
    #1 {main}

This is in the content, profile, billboard, news module

**Comment by fiammybe** [comment]
Looking at this, it seems that the problem exists at 'include_once "admin_header.php"' (line 58 in admin/content.php). 

I changed this to require_once, but it gives me no error.

**Comment by skenow** [comment]
Is this similar to the editor include_once issue? #305 - include_once returns 'true' on subsequent calls. instead of including the file

**Comment by skenow** [comment]
I found it too - installed my upcoming revision of Simplywiki and went to the admin page for it. Fatal error: call to undefined function. With our debug dashboard on, it shows multiple warnings about being unable to include files. All my paths are relative and with the relocation of the modules folder, how do we adjust?

**Comment by fiammybe** [comment]
I managed to find a first problem: if your module is built with the constructor module (as are most of the more recent ones), then in the 'include/admin_header.php' file you are including the 'cp_header.php' file in the wrong place (that file is no longer under the htdocs/include/cp_header.php location. 

When I adapt that, I get further :-)

However, I get an issue on the main module file, where my module wants to access the $icmsModule->displayAdminMenu function, and for some reason the $icmsModule global variable is null. Any ideas?

**Comment by fiammybe** [comment]
Looks like this fix doesn't solve the problem. I still have 
```
Uncaught exception
Message: Call to undefined function icms_cp_header()
Code: 0
File: /icmsroot/modules/tools/admin/index.php
Line: 24
Trace:

#0 /icmsroot/htdocs/index.php(115): require()
#1 {main}
```
for example in the 'tools' module
