### ISSUE TITLE
Update HTTMLPurifier to support HTML5

### ISSUE THREAD

**Issue by fiammybe** [ImpressCMS/impresscms#303]
Verify that the values that we have in the ACP are still in line with the values that are supported by HTMLPurifier in its latest version.

**Comment by fiammybe** [comment]
OK, so I thought that we didn't have HTML5 support in our library because we were behind in what HTMLPurifier could offer, but it turns out that the vanilla HTMLPurifier does not officially support HTML5. 

I found this : https://github.com/xemlock/htmlpurifier-html5, which offers a HTML5-compatible HTMLPurifier.

We will have to adapt our declaration of the HTMLPurifier library to match this new one, should we decide to use it.

**Comment by fiammybe** [comment]
This might even be a good improvement for the 1.3 branch, given that HTML5 isn't that novel anymore and widely usd :-)

**Comment by skenow** [comment]
ezyang's HTMLPurifier library does include another library to extend coverage to HTML5 tags - see libraries/htmlpurifier/standalone/Lexer/PH5P.php. The 4.15.0 version has PHP8.1 fixes in this file.

**Comment by fiammybe** [comment]
in that case, I think we can close this issue.
