### ISSUE TITLE
Enabled editor selector in system preferences is blank

### ISSUE THREAD

**Issue by skenow** [ImpressCMS/impresscms#305]
In the control panel, the enabled editor selector is empty and does not contain any editors. The default editor does contain the appropriate list. 

Related errors in the debug panel: 
Warning: array_keys() expects parameter 1 to be array, boolean given in file /libraries/icms/plugins/EditorHandler.php line 128
Warning: Invalid argument supplied for foreach() in file /libraries/icms/plugins/EditorHandler.php line 134
Warning: include_once(/cache/sourceeditor_list.php): failed to open stream: No such file or directory in file /libraries/icms/plugins/EditorHandler.php line 107
Warning: include_once(): Failed opening '/cache/sourceeditor_list.php' for inclusion (include_path='.:/usr/share/php') in file /libraries/icms/plugins/EditorHandler.php line 107

**Comment by skenow** [comment]
When I remove the include at the beginning of the getList method of icms_plugins_EditorHandler(), the multi-select box is filled properly. I also discovered the path in the include is missing a directory separator - fixing that did not fix this issue.

**Comment by skenow** [comment]
I installed in another environment and the issue does not occur there. The issue occurred in my most used dev environment, so I'm not sure what may be different there. I will need to compare apache and php settings.

**Comment by skenow** [comment]
I found no significant differences in the environments, and found that my second environment was not creating the editor list files, and therefore the include_once statement was failing and the list was being generated each time.

The getList method is being invoked twice for the standard editor list on the preferences page - once for the dropdown selector for the default, and once again for the enabled editors - and the 2nd time, only returns 'true' instead of the contents of the file. This follows the behavior documented by PHP - php.net/include_once

In the past, this file check was always false, since the path was incorrect, therefore, it never created this error.

Easy remedy: fix the path and change to include instead of include_once

Other suggestions?

**Comment by MekDrop** [comment]
In icms 2.0 I think I have already fixed that when I have added caching classes. For 1.3.x I think this should work better:
... replace this line:
```php
$list = @include_once ICMS_CACHE_PATH . $this->_type . 'editor_list.php';
```
... with
```php
static $list = null;
$cache_file = ICMS_CACHE_PATH . $this->_type . 'editor_list.php';
if ($list === null && file_exists($cache_file)) {
    $list = include($cache_file);
}
```
I think it should work everything fine after these changes.

**Comment by skenow** [comment]
Merged in PR318
