### ISSUE TITLE
Include available languages in distribution

### ISSUE THREAD

**Issue by fiammybe** [ImpressCMS/impresscms#316]
ImpressCMS is multi-language, include the best available languages in the distribution to put that in evidence.

Included : EN, DE, NL, FR, IT

If other languages can be added, that would be great, but we need a certain level of completeness

**Comment by skenow** [comment]
Related: I'm updating the links in 1.3 for our recombined sites and left the language packs alone. They did not get moved to the downloads module after we lost addons subsite. There are some on SourceForge still. The installer mentions Korean, Dutch, Japanese, German, Italian, Persian, and Spanish. Thoughts on this?

**Comment by fiammybe** [comment]
There is a great need to improve the download module, so that it at least takes links from sourceforge as well as local packages. The best would be to have a functionality that discovers and downloads languages on-the-fly for the installer

**Comment by fiammybe** [comment]
In the short term, I'll remove the buttons for the other languages, as they have no 1.3 version on Sourceforge. The link will stay, and will point to the location on sourceforge with the languages.

**Comment by fiammybe** [comment]
We can look at Transifex (https://www.transifex.com) for the other languages that are mostly complete.
