### ISSUE TITLE
Update links to ImpressCMS site resources

### ISSUE THREAD

**Issue by skenow** [ImpressCMS/impresscms#319]
Since we have combined our sites (api, addons, blog, community, and wiki), and changed modules, many of the resource links are no longer accurate.

**Comment by skenow** [comment]
What is our email subscription URL? The current one is incorrect.

**Comment by skenow** [comment]
I signed in and got the Mailchimp signup URL

**Comment by fiammybe** [comment]
OK, thanks. I’m in Italy on holiday at the moment and only saw your message now.

**Comment by skenow** [comment]
I'm on vacation too - out in the scenic Black Hills of South Dakota. It's not Italy, but it's beautiful!

**Comment by skenow** [comment]
Changes merged - closing #319
