### ISSUE TITLE
Random (?) text appears on pages

### ISSUE THREAD

**Issue by skenow** [ImpressCMS/impresscms#320]
With the current code in retro, there is a '7' that appears in different parts of the page that does not originate with any other content.

![image](https://user-images.githubusercontent.com/2429107/43300061-b7bb62aa-9122-11e8-845c-8a4585befb2f.png)

**Comment by skenow** [comment]
The ‘7’ is what is being assigned to the template var $icms_contents when there is no content (found using Smarty debug mode)

**Comment by MekDrop** [comment]
I think this is mistype. So, probably we could delete 7 and that's all.

**Comment by fiammybe** [comment]
I noticed that as well, I thought it was because it is the 7th alpha, but it is something that shouldn’t be there 😊
