### ISSUE TITLE
Add Slack badge to README

### ISSUE THREAD

**Issue by MekDrop** [ImpressCMS/impresscms#346]
I think Slack badge on https://github.com/GitbookIO/gitbook looks good. And I think it would be good to add something like this to our README. Maybe more users would join our chat system and maybe more users would be involved. Yes, I know that @fiammybe created another chat system on Gitter but we don't have so many users that I don't see any any point to have multiple chat systems for a while. I think Slack could be good enough for us for a while.

This badge is driven by [Slackin](https://github.com/rauchg/slackin). I think we could host this on Heroku or similar service as free hosting. That's not hard. But before that I need to get custom slack API app token from @fiammybe (yeah that's why I added you to here for this task!)

**Comment by fiammybe** [comment]
the reason I looked at gitter was because you do not need a slack account, and because I didn't want to look too much into slackin or similar services. I have no problem with slackin, we just need to set it up if we want it :-)

**Comment by fiammybe** [comment]
Hm, I looked at slackin, and it looks like Slack the API tokens are legacy (which means they can disappear in the very near future).

What do you think about this instead : https://small.chat/ ? Free option to see if it has some succes

**Comment by fiammybe** [comment]
True. I made you an admin, so you can try to setup slackin if you want :-)
