### ISSUE TITLE
Where are the module translations?

### ISSUE THREAD

**Issue by fiammybe** [ImpressCMS/impresscms#349]
I remember that there were quite a lot of translations for modules, but I can't seem to find them on sourceforge in the impresscms project. Any idea where those translations would be? I'm trying to get an overview of which language has which translation. I would like to cover the entire EU with translations, but there are quite a few that are missing :-)

**Comment by MekDrop** [comment]
Here https://www.transifex.com/ImpressCMS/public/ ? Or maybe somewhere on Assembla SVN? :|

**Comment by fiammybe** [comment]
Looked there, and I can't find any. I'll try to contact people from the japanese and german community to see if they still have some language packs somewhere.

**Comment by skenow** [comment]
I recall a lot of the module translations were in the module repo - with the module. That's how it was with SimplyWiki (made it difficult to use hinting in developing)

**Comment by skenow** [comment]
If you look on Assembla, some of the modules have multiple translations in their language folders -https://app.assembla.com/spaces/impresscmsaddons/subversion/source/HEAD/modules

**Comment by fiammybe** [comment]
That is correct. thanks! Once we decide to use transifex or crowdin (see #344 ) I'll setup the translation section for the modules that are still active and upload the translations there.
