### ISSUE TITLE
captcha form element not working

### ISSUE THREAD

**Issue by fiammybe** [ImpressCMS/impresscms#354]
I was testing how to create a new user on PHP 7.2, but the captcha image was not shown. When loading the image specifically, I get the error message (in dutch) : De afbeelding ‘http://localhost/davidjanssens/htdocs/libraries/icms/form/elements/captcha/img.php?refresh=0.5230098703065242’ kan niet worden weergegeven, omdat deze fouten bevat.

The image cannot be shown, because it contains errors.

**Comment by MekDrop** [comment]
is there something written in system php or webserver log file?

**Comment by fiammybe** [comment]
Not that I can see, no. I will try reinstalling my xampp, because the Database looks as if it is having configuration problems. So perhaps it is just a broken build I'm using.

**Comment by fiammybe** [comment]
I tried it again with a new setup, and there is no image shown.
