### ISSUE TITLE
Installer does not create users

### ISSUE THREAD

**Issue by fiammybe** [ImpressCMS/impresscms#355]
When I go through the installation routine in PHP 7.2, I get a perfectly working site, but the user table is empty. Looking at the installer, I get the 'failed to write 1 entry' in the user table : 
![afbeelding](https://user-images.githubusercontent.com/3736946/49908113-5d066c00-fe79-11e8-8ec7-82bf39a12f1f.png)

**Comment by fiammybe** [comment]
confirmed with PHP 7.1, mySQL 5.7 as well : the user table is empty.

**Comment by fiammybe** [comment]
looks like the insert in makedata.php is not having the same columns as there are in the table. Perhaps a result of #333 ?

**Comment by skenow** [comment]
I agree - the users table no longer has the IM columns and the insert statement for the installer did not line up.
