### ISSUE TITLE
BBCode is transformed in HTML, which breaks content from previous versions

### ISSUE THREAD

**Issue by fiammybe** [ImpressCMS/impresscms#361]
When looking at the forums on the site, the BBCode is no longer displayed correctly since the upgrade to 1.3.11. 
Problem description from @skenow : 

> The encoded content you see in those posts are code snippets and you can see the real text if you edit the post. However, if you save the post, the content is saved as encoded
> A new install of 1.3.11 Final does not exhibit this problem. There was a change merged into the 1.3.11 release regarding the icms_core_DataFilter::codePreConv and icms_core_DataFilter::codeConv methods to pass strict validation and preg_replace with /e. (edited) 
> The content in the posts was saved prior to any filtering and the bbcode tags are still there. In new releases, the tags are converted and saved as HTML

**Comment by skenow** [comment]
The updated method for codePreConv is missing the code tags in the return. Instead of
`return base64_encode($match[1]);`
it should be 
`return '[code]' . base64_encode($match[1]) . '[/code]';`

**Comment by thunderer** [comment]
@fiammybe @skenow Would you like to evaluate a new BBCode processing library? Please let me know what do you think about this: https://github.com/thunderer/Shortcode.

**Comment by thunderer** [comment]
Thanks for the suggestion, I'll add a comment on #207 so that you don't have to go back here.

**Comment by skenow** [comment]
This was closed with PR #362
