### ISSUE TITLE
make the htdocs folder name a configuration item

### ISSUE THREAD

**Issue by fiammybe** [ImpressCMS/impresscms#376]
Different server setups have different naming conventions. For example, my hosting on Directadmin doesn't use htdocs as the apache root, but uses the public_html and private_html folders.

The apache root folder should be detected by the installer, and it should be a configuration item in order to make the site work.

**Comment by MekDrop** [comment]
I created new [imponeer/composer-web-installer-maker](https://github.com/imponeer/composer-web-installer-maker) project that will be used as installer base for our projects. So, any feature related issues should be created from now there.
