### ISSUE TITLE
Start using Composer

### ISSUE THREAD

**Issue by MekDrop** [ImpressCMS/impresscms#381]
Composer is turning to be the standard tool in the PHP world to handle packages. Composer in combination with Github has changed the way most PHP programs are structured and developed. ImpressCMS should be more aligned with the PHP world if we are to attact developments from outside the current small group of enthousiasts.

Current state of the package
Moving to the use of composer will have an impact on how the current package is organised
* the project currently includes several external PHP libraries inside its own repository, in the medium term those libraries should be removed. Extracting those libraries might prove to be an important task in terms of time, given that the way composer works, you cannot hardcode the location of your library (the way we did until now), but you must use the composer autocompleter. Rewriting the necessary classes so that they keep working in a composer-handled ImpressCMS will not be easy
* A build will be needed starting from the composer file to get the distributable file. This means that it will no longer be possible to deploy directly from Git. When a build is done, the autoloader is pre-populated so that the classes are found.
* The installation/uninstallation of modules needs to be adapted so that the module classes are added to the autoloader by re-running the autoloader after every installation.
* The module overview screen should be rewritten to only take into consideration the data inside of the composer.lock file. That is a json file that gives the information about installed libraries and which corresponds with what is in the autoloader. No more icms_version.php. The good news : The information in the icms_version.php can normally be added to the composer.json file one way or another
* Composer offers a structured way of installing and following up patches to your code.
* Modules will need to add a composer.json file to their root
* We will need to offer a ImpressCMS-specific repository with addons for ImpressCMS. It should be coupled with at least github, so new releases of a module on Github get pushed automatically to that repository as well.
* I created a composer extension, https://github.com/ImpressCMS/composer-module-installer-plugin , which should take care of installing an ImpressCMS module in the right location using composer. It is basic, but it's a good start to implement the rest.

**Comment by MekDrop** [comment]
I think we should close this one. We have started using composer as title says. Some things are already implemented in this list. For other things we can create pull requests or open new single issues.

**Comment by fiammybe** [comment]
you are correct, this ticket was way too large :-)
