### ISSUE TITLE
Composer files not in sync with GitHub

### ISSUE THREAD

**Issue by mambax7** [ImpressCMS/impresscms#395]
FYI - the function checkModuleAccess($module, $inAdmin = FALSE) in \libraries\icms\module\Handler.php
is set to protected in Composer, while in GitHub is set as public (which is the correct way)

**Comment by skenow** [comment]
Thanks, Michael - we'll look into it. It appears the code style is also changed

**Comment by skenow** [comment]
In the 2.0 development branch, this method is public. In all of the 1.3 releases, it has been protected. Something else must be out of sync.
