### ISSUE TITLE
Use composer package for config

### ISSUE THREAD

**Issue by MekDrop** [ImpressCMS/impresscms#414]
[dflydev/dot-access-configuration](https://packagist.org/packages/dflydev/dot-access-configuration) seems like a good option to have Laravel style configuration.

**Comment by fiammybe** [comment]
That would be great! I'm not such a big fan of storing the configuration in a database. having the configuration in a file would mean that you can put the config of your site in Git (or  some other source control) and version that

**Comment by fiammybe** [comment]
we could consider youbs/dflydev-dot-access-configuration, as it looks like it fixes a bug
