### ISSUE TITLE
db_manager has deprecated constructor

### ISSUE THREAD

**Issue by fiammybe** [ImpressCMS/impresscms#418]
While doing the migration of the installer to PHP 7.2, I got the following deprecation notice : Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; db_manager has a deprecated constructor in C:\xampp72\htdocs\icms13php7\install\class\dbmanager.php on line 47

very probably this page will no longer work under PHP 7.3 :-(

**Comment by MekDrop** [comment]
I think you can copy db classes from 2.0 before .env commits. I think this one should work -> https://github.com/ImpressCMS/impresscms/blob/82c8399c1366b18b4807a76556cd60cde474e6f3/htdocs/install/class/dbmanager.php
