### ISSUE TITLE
Installer does not update the db version

### ISSUE THREAD

**Issue by skenow** [ImpressCMS/impresscms#470]
The installation of 1.4 does not update the system module, and when you access the admin area you are prompted to update the system module. Every time.

**Comment by fiammybe** [comment]
looks like a but in the launch of the upgrade procedure. I'll look into it.

**Comment by skenow** [comment]
It looks like the final instruction for updating the DB version is missing 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by skenow** [comment]
Merged fix from @fiammybe
