### ISSUE TITLE
icms_core_Object::cleanVars generates PHP7 errors

### ISSUE THREAD

**Issue by skenow** [ImpressCMS/impresscms#477]
'continue' on lines 515 and 566 are equivalent to 'break'. Should it be 'break' or 'continue 2'?

**Comment by MekDrop** [comment]
There is one difference: break will add variable into cleanVars array but continue will skip. I'm not sure if we need something for these cases in that array or not.

**Comment by skenow** [comment]
The conditions being tested at those points look like they should terminate, as the others do - continuing on to the next test doesn't make sense to me.

**Comment by fiammybe** [comment]
agreed, changing this to 'break' as well
