### ISSUE TITLE
automatic redirect to index.php is not happening

### ISSUE THREAD

**Issue by fiammybe** [ImpressCMS/impresscms#489]
When launching a site, it should redirect to /htdocs/index.php. That means, if you go to /htdocs/, the site should redirect to index.php and all would be well.
That redirection doesn't happen, not on the home nor on the admin page.

This was also one of the issues mentioned in #266

**Comment by skenow** [comment]
That is a server directive - for our purposes: "DirectoryIndex disabled index.php index.html" 

If the server is set for "DirectoryIndex disabled", nothing will be displayed. It can be overridden by .htaccess, and Apache docs recommend against using .htaccess, except when no other alternative exists. https://cwiki.apache.org/confluence/display/HTTPD/Htaccess#
