### ISSUE TITLE
Minimum PHP requirements are inaccurate

### ISSUE THREAD

**Issue by skenow** [ImpressCMS/impresscms#494]
The help text displays PHP 5.5 as the minimum requirement since ImpressCMS 1.3.9, the tests are still for PHP 5.2, sites are running ImpressCMS 1.3.11 on PHP 5.4 - the requirements are unclear.

**Comment by fiammybe** [comment]
We now publish and test 5.6 as the minimum, even if that version is out of maitenance for a while now. 

Running a site on 5.4 is possible, but it is a risk running on an old, slow version without support. 

Other topic: we should probably think about some validation of the environment before starting an update. You don't want to update to find your environment is no longer compatible with the new version you just used to crush your previous version with :-) But that's a discussion for the module and installation handling

**Comment by fiammybe** [comment]
merged in #505
