### ISSUE TITLE
14RC - trustpath creation does not work

### ISSUE THREAD

**Issue by fiammybe** [ImpressCMS/impresscms#569]
## Describe the bug
I cannot create a trustpath, nor make the system detect one

## To Reproduce
When I arrive on the installation page where I need to set the trustpath, the trustpath folder is pre-filled to a random value. Of course this value doens't exist. Clicking on the button 'create trustpath' has no effect. Also, refreshing the page while having created the trustpath manually doesn't change the status of that field.

## Expected behavior
I click on the 'create trusthpath' button and the trustpath that is mentioned in the field above is created.
When I exit the field, a new check is done to see if the trustpath exists at that moment.

## Server Setup
 - HTTP Server : Apache
 - HTTP Server Version : 2.4
 - HTTP Server is 32/64bit
 - PHP Version : 7.2
 - PHP is 32/64bit
## Desktop (please complete the following information):
 - OS: Windows 10
 - Browser FireFox + Chrome
 - Version 70.0.1

## Additional context
None

**Comment by fiammybe** [comment]
This is the last ticket that keeps me from releasing 1.4 RC. I narrowed it down to a problem in the install/pathsettings.js, but my Javascript is non-existent. @MekDrop Could it be related to the use of Prototype?

**Comment by MekDrop** [comment]
A bit later or tomorrow I will look into. I think I had similar issue some time ago but I can't remember what happened.

**Comment by skenow** [comment]
The inclusion of prototype.js is interfering with the pathsettings.js. When I remove prototype.js inclusion, the buttons are given their proper event listeners.

**Comment by skenow** [comment]
Moving prototype.js inclusion to page_dbsettings.php seems to resolve the trust_path creation issue and still work on the collation selection

**Comment by fiammybe** [comment]
Thanks for this, this fix works as expected, so I can now start release of 1.4.0 RC.
