### ISSUE TITLE
Include new editor CKEditor as option

### ISSUE THREAD

**Issue by fiammybe** [ImpressCMS/impresscms#570]
## Describe the bug
The current default editor is the old and rusty HTML editor. Other options are FCK editor, which is ancient as well. Upgrade this please!

## To Reproduce
Create content

## Expected behavior
The base editor is the CKEditor

**Comment by fiammybe** [comment]
this is beyond the scope of 1.4.0, but would be a good fit for both 1.4.1 and 2.0.
There is a working CKEditor 4.5.3 editor around, but it needs some updates to make it more generic.

**Comment by MekDrop** [comment]
For 2.0 once possible (when we I will able to figure out what todo with assets - #134) I plan to add [summernote](https://summernote.org) or any other similar editor as default. It's lightweight but also extensible.

**Comment by fiammybe** [comment]
Great find! At the moment all our editors are based on the fact that they extend a htmltextarea. Summernote is more flexible, it uses a div with a specific ID that you can choose yourself.
We'll need to take this into account on the editor side before we can start writing integrations with this kind of editors.

But overall 👍

**Comment by skenow** [comment]
The limitation on how to insert into the page is not the editor, but the decision to support the legacy editor and allow replacement with another editor of choice., without having to resort to a lot of hacks when switching - the same elements are used for all editors.

CKEditor 5 is still quite viable. Our role is to build the hooks and allow freedoms to choose any modern editor.

**Comment by skenow** [comment]
This [comparison](https://medium.com/maatwebsite/lets-see-wyg-with-these-editors-e5720e91a626) is quite thorough - compatibility with the 'new' IE (Edge, may it be as good as IE6 ;-) )

**Comment by fiammybe** [comment]
Nice comparison, and I see CKeditor 5 comes up last :-( However I think including CKEditor 4 or 5 in the core now, without forcing anyone to switch at the moment, will give the choice for those that want to use newer editors, and keep us from having to write an automated conversion for the moment.
Forcing is not a good way, not until a reasonable migration period is communicated first.

**Comment by skenow** [comment]
There is a repository for CKeditor as an editor for ImpressCMS - https://github.com/skenow/impresscms-ckeditor.git 

I have it working on some production sites.

**Comment by fiammybe** [comment]
This was included in the 1.4.3 release
