### ISSUE TITLE
Replace current authentication system with a more flexible one

### ISSUE THREAD

**Issue by fiammybe** [ImpressCMS/impresscms#575]
Our current authentication system pre-dates the arrival of social authentication, with the exception of the old OpenID login.
This needs to be replaced to give our users the possibility to leverage social logins (Facebook, Twitter, Google, Yahoo, Github, Bitbucket, ...) as well as generic OAuth and if possible also LDAP/ActiveDirectory.

**Comment by fiammybe** [comment]
Some possibilities : 
- OpAuth : https://www.opauth.org/ (1,7K stars on Github)
- SocialConnect : https://github.com/SocialConnect (379 stars on Github)
- HybridAuth : https://packagist.org/packages/hybridauth/hybridauth (3K stars on Github)

**Comment by MekDrop** [comment]
I already did some experiments with [Aura Auth](https://github.com/auraphp/Aura.Auth). At first I will add PDO and LDAP support. Other options will come later. Once #550 will be accepted.

**Comment by fiammybe** [comment]
When looking at Aura Auth I see that they have no pre-built connectors for Twitter, Facebook, Linkedin and the likes, at least i couldn't find them.

**Comment by MekDrop** [comment]
In aura auth docs there is example how to use with OAuth and that is what Twitter, FB, LinkedIn and many more uses. I think that is enough for us.

**Comment by fiammybe** [comment]
the others in the list only focus on the social login, which aura auth does not (LDAP, social +local), so we'll go with that one.
