### ISSUE TITLE
ImageManager : admin can no longer preview images

### ISSUE THREAD

**Issue by fiammybe** [ImpressCMS/impresscms#590]
based upon bug report by Peter-Michael Priebs (pmp-webdesign)
## Describe the bug
As admin I can no longer preview images in the Image Manager

## Screenshots
see PDF in attachment

## Additional context
both on 1.3.11 or 1.4.0 (clean and upgrade)
[Imagemanager.pdf](https://github.com/ImpressCMS/impresscms/files/4059387/Imagemanager.pdf)

**Comment by skenow** [comment]
In the screenshot, only the categories without any images cannot be previewed. If you add images, can you preview them?

**Comment by fiammybe** [comment]
I added an image to the logos category, and now it says there are 2 images in the category, but only the header is displayed, and no images.

**Comment by skenow** [comment]
Fresh install of 1.4.0 - 1 category and 1 image. I am able to preview the category, and the image is not displayed.

Debug shows -

> Smarty error: unable to read resource: "db:admin/images/system_adm_imagemanager_img.html" in file /libraries/smarty/Smarty.class.php line 843
> Smarty error: unable to read resource: "db:admin/images/system_adm_imagemanager_editimg.html" in file /libraries/smarty/Smarty.class.php line 843
> Smarty error: unable to read resource: "db:admin/images/system_adm_imagemanager_cloneimg.html" in file /libraries/smarty/Smarty.class.php line 843
