### ISSUE TITLE
Existence of banners folder results in errors

### ISSUE THREAD

**Issue by skenow** [ImpressCMS/impresscms#600]
## Describe the bug
The banner submodule has only been partially removed - modules/system/admin/banners/ still exists, and because of this, errors are generated trying to load files in /modules/system/blocks/system_admin_blocks.php (line 120)

## To Reproduce
Enable developer dashboard
View errors on the main admin page

**Comment by fiammybe** [comment]
this has been taken care of, the errors  no longer appear.
