### ISSUE TITLE
Issue with image inclusion on TinyMCE in 1.4

### ISSUE THREAD

**Issue by fiammybe** [ImpressCMS/impresscms#603]
## Describe the bug
As described by PMP-webdesign : There are issues including images in TinyMCE in ImpressCMS 1.4

## Expected behavior
I can include an image when my standard editor is TinyMCE, but it doesn't work.

**Comment by fiammybe** [comment]
I asked about the version of TinyMCE and the used browser. Perhaps it is time to Bump our version of TinyMCE as well?

**Comment by skenow** [comment]
I'm reopening this - during testing of the input filtering, I verified the plugin does not display the images when you view a category. It does not work when using the imagemanager in the core DHTML editor, either.

Debug errors: 
unable to read resource: "/modules/system/templates/admin/images/system_popup_imagemanager_img.html"
unable to read resource: "/modules/system/templates/admin/images/system_popup_imagemanager_editimg.html"
unable to read resource: "/modules/system/templates/admin/images/system_popup_imagemanager_cloneimg.html"
