### ISSUE TITLE
Upgrade of the system module from 1.2 fails on 1.4

### ISSUE THREAD

**Issue by fiammybe** [ImpressCMS/impresscms#613]
## Describe the bug
As mentioned by @skenow on slack : Upgrade from an old site to 1.4 fails with the upgrade" of the system module

## To Reproduce
the system module update fails immediately. Changed the value in modules/system/icms_version.php to '1311' and updated the version - the upgrade completed

## Expected behavior
Even though the numbering scheme for modules was changed for 1.3.11, an 'old' value should be handled gracefully.

## Additional context
Upgrade from a 1.2.X site

**Comment by fiammybe** [comment]
I wonder if casting the value as string would help, I'll try that out.

**Comment by skenow** [comment]
It may take more than that - at least test for the value of the module version in the version file before proceeding. Is the numeric value the same as the string value? If it is, do one thing. If not, do another.
