### ISSUE TITLE
Routing Error on all pages on fresh 2.0 alpha 10 installation

### ISSUE THREAD

**Issue by fiammybe** [ImpressCMS/impresscms#785]
## Describe the bug
Tested on PHP 7.3 and PHP 7.4 : after finishing the installation routine, the frontpage (and also user.php, admin.php, ...) gives a 404 error in the ImpressCMS 2.0 Alpha 10 build as mentioned on https://www.impresscms.org/modules/iforum/viewtopic.php?topic_id=5900&post_id=50708#forumpost50708

## To Reproduce
1. Install impressCMS 2.0 a 10
2. go to the homepage
3. See error

## Expected behavior
I expect at least the front page to show

## Server
 - PHP version: 7.3 and 7.4
 - PHP is 32/64bit: 64
 - HTTP Server : [Apache, nginx] Apache (XAMPP)
 - HTTP Server version: 2.4.41
 - HTTP Server is 32/64 bit: 64
 
## Additional context
The composer installation was composer 2.0 RC1

**Comment by fiammybe** [comment]
of course, this is in a subfolder

**Comment by MekDrop** [comment]
I think this is due never composer. I'm still trying to find a solution.

**Comment by fiammybe** [comment]
It is true that I was using composer 2 RC1 at the time...
