### ISSUE TITLE
using mysql_connect in installation - unsupported since php7

### ISSUE THREAD

**Issue by fiammybe** [ImpressCMS/impresscms#79]
Even though I'm using the PDO connection, the installer still tries to connect to mysql with an unsupported function. When I do the setup on PHP 7.0.9 I get the following : 

> Fatal error: Uncaught Error: Call to undefined function mysql_connect() in C:\xampp70\htdocs\icms1310\install\page_dbconnection.php:50 Stack trace: #0 {main} thrown in C:\xampp70\htdocs\icms1310\install\page_dbconnection.php on line 50

in file icms1310/install/page_dbconnection.php

**Comment by fiammybe** [comment]
okay, like @skenow already mentioned, this is not a simple fix. PHP7 support is a requirement for 2.0 (as it will be the only version still supported by the time we release), so I propose to rewrite this part and make it simpler : only PDO.

**Comment by MekDrop** [comment]
I already have half needed code in my DB rewrite branch (mongodb and pdo) :) I just need somehow just to finish.

**Comment by fiammybe** [comment]
Great news, I'll have a look at what you did there

Op do 26 jan. 2017 09:18 schreef Raimondas Rimkevičius <
notifications@github.com>:

**Comment by MekDrop** [comment]
I think you should wait a bit. At current stage my code is messed up ;( I need to find some time to fix it.
