### ISSUE TITLE
error page when visiting the editor admin page

### ISSUE THREAD

**Issue by fiammybe** [ImpressCMS/impresscms#804]
## Describe the bug
When I want to visit the editor admin page, I get an error :
`Fatal error: Uncaught Error: Call to a member function getAlias() on null in /home/x/domains/xxx/public_html/beta/core/Extensions/Editors/EditorsRegistry.php:153 Stack trace: #0 /home/x/domains/xxx/public_html/beta/core/Extensions/Editors/EditorsRegistry.php(230): ImpressCMS\Core\Extensions\Editors\EditorsRegistry->getList() #1 /home/xxx/domains/xxx/public_html/beta/modules/system/admin/preferences.php(205): ImpressCMS\Core\Extensions\Editors\EditorsRegistry::getListByType('') #2 /home/xxx/domains/xxx/public_html/beta/modules/system/admin.php(113): include_once('/home/xxx...') #3 /home/xxx/domains/xxx/public_html/beta/core/Controllers/LegacyController.php(56): require('/home/xxx...') #4 /home/xxx/domains/xxx/public_html/beta/vendor/league/route/src/Strategy/ApplicationStrategy.php(23): ImpressCMS\Core\Controllers\LegacyController->proxy(Object(GuzzleHttp\Psr7\ServerRequest), Array) #5 /home/xxx/domains/imp in /home/xxx/domains/xxx/public_html/beta/core/Extensions/Editors/EditorsRegistry.php on line 153`

## To Reproduce
1. Go to '/htdocs/modules/system/admin.php?fct=preferences&op=show&confcat_id=1'
2. See error

**Comment by MekDrop** [comment]
I think I have fixed this with #800 . This is also composer v2.x related bug.

**Comment by fiammybe** [comment]
this is no longer there. Fixed
