### ISSUE TITLE
Missing templates in system module

### ISSUE THREAD

**Issue by skenow** [ImpressCMS/impresscms#805]
## Describe the bug
Using the core image manager and the dhtmleditor, no images are displayed in the popup

## To Reproduce
1. Edit a text area using the dhtmleditor - in either the user side or admin area
2. Click on the imagemanager icon in the toolbar
3. See error

## Expected behavior
Image categories should be displayed and images can be viewed and selected

**Comment by fiammybe** [comment]
I was under the impression that this was already fixed several months ago in the 1.4.1 release, to be honest.

**Comment by skenow** [comment]
There were 5 or 6 still not in the list
