### ISSUE TITLE
Can't access content.php (Missing module?)

### ISSUE THREAD

**Issue by jrckmcsb** [ImpressCMS/impresscms#808]
## Describe the bug
Setting up a copy of ImpressCMS for testing purposes and it seems the main modules are missing.  Current version **1.4.1**

## To Reproduce
1. Grab a copy of Impress CMS from this repo (select the 1.4 branch)
2. Install it
3. Assume you successfully install it, go to ``htdocs/content.php``

## Expected behavior
Can access the ``content.php``

![_1](https://user-images.githubusercontent.com/62977259/99463400-9bafd580-2970-11eb-938a-313d02a1b129.png)

## Additional context
On this version the only module that included is the ``protector`` module. 
No other modules.. 

![_2](https://user-images.githubusercontent.com/62977259/99463738-635cc700-2971-11eb-8b5c-4f92f880c24c.png)

**Comment by fiammybe** [comment]
Hello, did you download the impresscms-1.4.1.zip file from the release, or did you get the source code archive? 

The core modules (content and profile) are developed in their own repositories, and are added to the release zip files. As far as I know, there is no way to remove the source code archive, but that archive does not contain the mentioned modules.

**Comment by jrckmcsb** [comment]
I am not sure if I download the right source code
-> https://github.com/ImpressCMS/impresscms/tree/branches/impresscms_1.4 
-> https://sourceforge.net/projects/impresscms/files/1.4.1/v1.4.1.zip/download
I am not sure if these link contains the release file (I already test the link on sourceforge) and here is the result : 
![_3](https://user-images.githubusercontent.com/62977259/99466509-7ffbfd80-2977-11eb-9647-37378a67ac7d.png)

Can you share the release file link ?

**Comment by fiammybe** [comment]
you are correct, on sourceforge the archive was not correct. I'm uploading a new version as we speak, and then I'll have to adapt th elinks on the Github release.

**Comment by fiammybe** [comment]
the link to the 1.4.1 release file is https://sourceforge.net/projects/impresscms/files/latest/download

**Comment by fiammybe** [comment]
and the release now also points to the correct file, with the 2 modules included. Let me know if you are succesful in installing

**Comment by jrckmcsb** [comment]
Thank you @fiammybe 
![_4](https://user-images.githubusercontent.com/62977259/99468217-0c5bef80-297b-11eb-8a09-2280d7aced4e.png)


Just a quick question. 1.4.1 is part of "on-scope" for Hackerone?

**Comment by fiammybe** [comment]
yes it is
