### ISSUE TITLE
Update icms_get_base_domain in installer functions - domain list is outdated

### ISSUE THREAD

**Issue by fiammybe** [ImpressCMS/impresscms#83]
THe domain list to determine the base domain is outdated. I'm not so sure that this is still the best approach, given the multitude off new top-level domains that are added almost weekly.
Perhaps a regex-based approach will prove to be more future-proof

**Comment by MekDrop** [comment]
I think we could offer [league/uri](https://uri.thephpleague.com/5.0/) for working with urls. This function from what I see was used in system module upgrade scripts. I'm not sure if it isn't used somewhere else but I think after #246 will be merged `icms_get_base_domain` could be removed from core. 

Same probably could be done with `icms_get_url_domain` that is used also only in `icms_get_base_domain` and system module upgrade scripts.
