### ISSUE TITLE
Use fxpio/composer-asset-plugin for front-end assets management

### ISSUE THREAD

**Issue by MekDrop** [ImpressCMS/impresscms#86]
[fxpio/composer-asset-plugin](https://github.com/fxpio/composer-asset-plugin) is amazing composer plug-in that let's include bower and npm libraries directly in composer.json. This will let easier to manage also front-end.

For example we can include jquery functionality in module by executing ``composer require bower-asset/jquery`` command and than with ``$icmsModuleTpl->load('jquery')``; we could add the library to the module theme.

**Comment by fiammybe** [comment]
I think I looked into this one before. Do you have experience with how it handles the files? There are lots of instances of these non - PHP projects l like jquery or bootstrap that exist on packaging, but the big problem with those are for me :
* composer is specialized in php handling. It needs all kinds of workarounds for other libraries 
* the javascript libraries that are managed through composer cannot use autoloader, so it's back to hard-coded paths and versions 

Would this library solve some (or all,  I still believe in Santa) of these problems?

**Comment by MekDrop** [comment]
Yes I have! Yesterday I have implemented this one in CRM where I work. Also, Yii2 use this plug-in.

I think there are 4 issues with fxpio/composer-asset-plugin:
1) It use flat dependencies like bower. So it would install only one version per library.
2) It's not a replacement for npm or bower. It's much more like emulator, so not everything is supported. 
3) It asks for a token from github to bypass files limit if you download many files.
4) Downloaded libraries are stored in `vendor/bower-asset` and `vendor/npm-asset` subfolders. So vendor folder must be accessible (or at least those subfolders) from webbrowser.
...but looking from what we have right now I think everything would look much better :) 

This plug-in doesn't solves a front autoloader issue. It's because that there are no standardized such thing.  The plug-in is basically only just for downloading assets and upgrading when needed.

**Comment by fiammybe** [comment]
I think this is certainly a solution worth investigating.

**Comment by MekDrop** [comment]
I think we should dismiss this idea. `fxpio/composer-asset-plugin` needs to be installed globally for work perfectly in any situation. And that would be a problem for many our users. Still I think we should look for other similar solution.
