### ISSUE TITLE
Remove unused color picker from includes

### ISSUE THREAD

**Issue by fiammybe** [ImpressCMS/impresscms#88]
As far as I can see, the files includes/color-picker.js and color-picker.html are not used. We should be able to safely remove them

**Comment by MekDrop** [comment]
Are you sure that we don't have any modules that uses that?

**Comment by skenow** [comment]
It is used by the icms form element ColorPicker - not sure what uses that, though

**Comment by skenow** [comment]
It's used in the personalization preferences
