### ISSUE TITLE
Trying to send mails with SMTPAuth gives mission 'SMTP' class

### ISSUE THREAD

**Issue by fiammybe** [ImpressCMS/impresscms#881]
## Describe the bug
I want to send mails using the Google SMTP servers, because I need to have DKIM support activated to combat spam an phising from my domain. The Google SMTP servers use SMTPAuth. When I activate that, I get the following error message : 

Fatal error: Class 'SMTP' not found in /xxx/libraries/phpmailer/class.phpmailer.php on line 2604

## To Reproduce
1. Login to your site
2. Go the the ACP
3. Go to System > Site Configuration > Preferences > Mail Setup
4. Mail Delivery : SMTPAuth, SMTP Hosts : smtp.gmail.com, SMTPAuth username and password corresponding to your user, SMTP Secure method : SSL, SMTP Port : 465
5. Go to System > Users and Groups > Mail Users
6. identify some users, set a text and a subject, and send
7. Get error

## Expected behavior
I would like to system to use the GMail servers to send my mail.

## ImpressCMS
- version : 1.4.2

## Server
 - PHP version: 5.6
 - PHP is 32/64bit: 64
 - HTTP Server : [Apache, nginx] Litespeed (apache compatible)
 - HTTP Server version: ?
 - HTTP Server is 32/64 bit: 64

**Comment by skenow** [comment]
This can be closed, then?

**Comment by fiammybe** [comment]
Yep, this can be closed
