### ISSUE TITLE
Suspicious concatenation

### ISSUE THREAD

**Issue by AppChecker** [ImpressCMS/impresscms#90]
Hi.

Please look this [section of code](https://github.com/ImpressCMS/impresscms/blob/0166fb5bef10ec522a20cdeb597c9771c3d3c835/upgrade/cnt-2.2.x-to-2.0.x/index.php#L382):
```
		$sql =  "   SELECT b.* " .
                "   FROM " . $xoopsDB->prefix("newblocks_bak") . " AS b LEFT JOIN " . $xoopsDB->prefix('block_instance') . " AS i ON b.bid = i.bid " .
                "   WHERE i.instanceid IS NULL";
                "   GROUP BY b.dirname, b.bid";
```
String  "   GROUP BY b.dirname, b.bid" is not involved in the concatenation operation.

Probably, it should be:
```
		$sql =  "   SELECT b.* " .
                "   FROM " . $xoopsDB->prefix("newblocks_bak") . " AS b LEFT JOIN " . $xoopsDB->prefix('block_instance') . " AS i ON b.bid = i.bid " .
                "   WHERE i.instanceid IS NULL".
                "   GROUP BY b.dirname, b.bid";
```

This possible defect found with [AppChecker](https://cnpo.ru/en/solutions/appchecker.php)

**Comment by fiammybe** [comment]
very very old code, probably never used anymore (migration from old XOOPS sites). Typo that breaks the select visibly.
