### ISSUE TITLE
Lower the required PHP to 5.5 again

### ISSUE THREAD

**Issue by fiammybe** [ImpressCMS/impresscms#93]
We don't really need PHP 5.6 at the moment, and I personally have a host that offers either PHP 5.5 or PHP 7.0, so we fall a bit in between. Let's lower to PHP 5.5 until we are ready to go to PHP 7

**Comment by MekDrop** [comment]
What do we need for PHP 7 ? Fix installer?

**Comment by fiammybe** [comment]
Not only that, I'm discovering step by step, but there are some things in the code as well.

**Comment by fiammybe** [comment]
See #79 for the installer bug.
