### ISSUE TITLE
Convert arrays to short syntax

### ISSUE THREAD

**Issue by fiammybe** [ImpressCMS/impresscms#94]
Now that we have at least PHP 5.5 as requirement, it might be interesting to start using the short syntax for arrays.
I see this as part of an initiative to update the coding style to be more aligned with the latest versions of PHP.

pro
--
* the square brackets make it easier to distinguish from the other brackets used for functions
* less stuff to type :-)
* it forces usage of at least PHP 5.4

con
--
* lots of files to revisit, although it is possible to convert it automatically using [https://github.com/thomasbachem/php-short-array-syntax-converter](url)

**Comment by MekDrop** [comment]
I think Netbeans has plug-in for that too!
