### ISSUE TITLE
Unable to update module

### ISSUE THREAD

**Issue by fiammybe** [ImpressCMS/impresscms#948]
## Describe the bug
I am unable to update modules (even the system module) in the latest version

## To Reproduce
1. Go to the module list page (/modules/system/admin.php?fct=modulesadmin)
2. Click on the update button next to a module
3. on the new page, click on the 'update' button
4. Nothing happens, return to acp home page

## Expected behavior
the module update procedure starts, listing the different installs or inserts n theDB that are done

## Server
 - PHP version: 7.4
 - PHP is 32/64bit: 64
 - HTTP Server : [Apache, nginx] Apache
 - HTTP Server version: 2.4
 - HTTP Server is 32/64 bit: 64

**Comment by fiammybe** [comment]
@skenow it looks like the 'fct' parameter is lost, and so the security settings throw back to the acp frontpage.

**Comment by skenow** [comment]
We can close this now - right @fiammybe ?

**Comment by fiammybe** [comment]
That is correct, I tested it and now this works. I hadn't noticed the language file issue yes, so that is a nice catch as well. Thanks!
