### ISSUE TITLE
Replace ImpressCMS legacy autoloader with Composer Autoloader

### ISSUE THREAD

**Issue by fiammybe** [ImpressCMS/impresscms#95]
ImpressCMS has a legacy autoloader that has some specific custom-built functionality for ImpressCMS, done at runtime.
* module classes are calculated every time as 'mod_' + module name + class name
* the core classes are handled specifically, linking the name of the class to the folder structure.

Using the composer autoloader changes this. Composer either auto-calculates the classes based on PSR-1 or PSR-4 class structures (which ImpressCMS isn't yet compatible with), or it pre-calculates the classes that are contained in folders defined in the composer.json file.

As a first step, we should replace the ImpressCMS autoloader with composer, based on pre-calculated class names for everything. That should work without fundamental changes in our code. Later steps will involve
* managing modules (we need to call composer to re-calculcate the classes to take into account the added/removed/updated module)
* extract the hard-coded paths for the included libraries and use the composer included libraries (smarty, wideimage, ...)
* create a webpage-based interface to discover, update, install and remove modules, translations, themes, preloads
* re-write the core classes structure following PSR-4 so that they use the PHP 5.3+ way of class structure (with backslashes and 'use' directives) so they can be auto-discovered by the compose autoloader

**Comment by fiammybe** [comment]
Part of this is already done, but it isn't managed in github. That's the reason for which I created this ticket. Not everything was clear for everyone after some discussions I had recently, another reason for the ticket :-)

**Comment by MekDrop** [comment]
This is 2.0.0 task?

**Comment by fiammybe** [comment]
yes, strictly 2.0. It could be backported to 1.3 but the priority at the moment is for this to be the backbone of the 2.0 functionalities

**Comment by fiammybe** [comment]
The autoloader by composer is used, but I'm not sure that it is used everywhere... There are some parts of code that try to generate classnames to include, so some cleanup will be needed I think.

**Comment by MekDrop** [comment]
I think we can close this issue for now. It seems it mostly works. If something happens we could than reopen or create new one.
