### ISSUE TITLE
HTMLPurifier is broken in specific case

### ISSUE THREAD

**Issue by fiammybe** [ImpressCMS/impresscms#97]
I installed madfish's 'events' module in 1.3.9, and it works without a problem. To take advantage of the new backend theme, I tried upgrading to 2.0. The upgrade works without a problem (don't forget to run composer update in the current distributed source), but when I want to create a new event, I get a blank screen.
I have narrowed it down to the place where HTMLPurifier loads its configuration (HTMLFilter.php:70), but there I'm a bit stuck. 

If we get this fixed, I think we can release a new 2.0 alpha.

**Comment by skenow** [comment]
I'll have a look at this - there are some lines that are suspect in that portion of code

**Comment by skenow** [comment]
I just installed Events 1.01 in the latest retro code - I didn't have any errors. I did have to run 'composer up' for it to install (I didn't install in 1.3.x and then upgrade). 

At what point did you get the blank screen? When you clicked on 'Add a event', or when you clicked on 'Submit' to create the event?

**Comment by fiammybe** [comment]
Issue is no longer present, visibly.
