### ISSUE TITLE
Module selection in Group Administration shows module ID, not module name

### ISSUE THREAD

**Issue by skenow** [ImpressCMS/impresscms#98]
All admin themes display the MID, rather than the module name when administering groups.

**Comment by skenow** [comment]
This also affects the search page, where you select which modules to search. Neither modules/system/admin/groups/groupform.php, which renders the groups admin page, nor include/searchform.php, have been altered recently. They both use $module_handler->getList() (icms_ipf_Handler::getList()) to retrieve the list of modules, which has been altered in 2.0.

I can't get a custom PHP block to display the results of getList in 2.0 - but the same lines produce output on 1.3.x

**Comment by skenow** [comment]
I've identified a part of the issue - $keyword is used in 2.0 instead of the object property $this->identifierName. However, $keyword is defined as $this->getIdentifierName(), which returns the object prefix by default. Making an adjustment for this, does help, but shows the module folder name, not the display name of the module. This goes back to the __construct method and how it is invoked.

I need to investigate further and see how much this impacts.

**Comment by fiammybe** [comment]
this is a very old ticket, is it still present in the current alpha?
